version: '3'
services:
  server:
    build: 
      context: ./server
      dockerfile: dockerfile
    image: server
    container_name: intake-server
    ports:
    - "8001:8001"
  app:
    build: .
    image: app
    container_name: intake-app
    ports:
    - "80:8080"
    depends_on:
    - server
    links:
    - server


  