version: '3.7'
services:
  db:
    build: 
      context: ./db
      dockerfile: dockerfile
    container_name: intake-db
    image: db
    ports:
    - "1433:1433"
    expose: 
    - "1433"
  server:
    build: 
      context: ./server
      dockerfile: dockerfile
    image: server
    container_name: intake-server
    ports:
    - "8001:8001"
    - "443:443"
    depends_on:
    - db
  app:
    build: .
    image: app
    container_name: intake-app
    ports:
    - "8080:8080"
    - "80:80"
    - "433:433"
    depends_on:
    - server
    - db