FROM node:lts

RUN mkdir usr/src/app
COPY ["package.json", "/usr/src/app"]
RUN cd /usr/src/app && npm install
WORKDIR usr/src/app
COPY [".", "/usr/src/app"]
EXPOSE 8001
EXPOSE 443
CMD [ "npm" , "start"] 
