FROM node:lts

RUN mkdir usr/src/app
COPY ["package.json", "/usr/src/app"]
WORKDIR usr/src/app
COPY [".", "/usr/src/app"]
RUN ls
RUN npm install
RUN ls
RUN node --version
EXPOSE 8001
EXPOSE 443
CMD [ "npm" , "start"] 
